### ISSUE TITLE
[discussion] Should we use Pod or Job to create the ModelJob?

### ISSUE THREAD

**Issue by gaocegege** [caicloud/temp-model-registry#6]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

https://github.com/caicloud/temp-model-registry/pull/4#discussion_r442724980

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
For me, I think there is no difference between Pod and Job.  Based on experience, what are the advantages of using Job?

**Comment by gaocegege** [comment]
Maintaining pod resources directly is hard. There are lots of ad-hoc cases. If we use Job, we reuse the job controller logic to some extend. The pod can be restarted when it fails with the help of job controller, and so on.

**Comment by simon-cj** [comment]
emmm, SGTM, I will update it by using Job.

**Comment by gaocegege** [comment]
I think we can keep using Pod now and see if we need to use Job actually. It is just a technical trade-off.
